### ISSUE TITLE
Caffe model

### ISSUE THREAD

**Issue by VirrageS** [VirrageS/io-kawiarnie#104]
Model kawiarni:
 - `name`
 - `address`
 - `created_on`
 - `creator`
 - `contact_email`

**Comment by martarozek** [comment]
Jeśli to mają być dane dla ludzi zarządzajacych aplikacją, to może
- data dołączenia do aplikacji,
- osoba kontaktowa/admin ?

**Comment by VirrageS** [comment]
Dodałem. Spoko?

**Comment by martarozek** [comment]
Myślę, że spoko. Tak naprawdę nie wiem czy komuś te dane będą kiedyś potrzebne, więc myślę, że tyle wystarczy. 😃
