### ISSUE TITLE
Add caffe relation to all models

### ISSUE THREAD

**Issue by VirrageS** [VirrageS/io-kawiarnie#108]
Trzeba dodać `caffe_id` do każdego modelu, żeby można było wiedzieć, z której jest on kawiarni.

- [x] Report
- [x] Category
- [x] FullProduct
- [x] Product

---

- [x] Stencil

---

- [x] CashReport
- [x] FullExpense
- [x] Expense
- [x] Company

---

- [x] WorkedHours
- [x] Position

---

- [x] Employee

**Comment by martarozek** [comment]
Wow co to za checkboxy? 🆒

**Comment by VirrageS** [comment]
Żeby można było zaznaczać, co jest zrobione, a co nie. Te "...." oznaczają, że trzeba tam jeszcze wypisać pozostałe modele ale to jutro zrobię.
