### ISSUE TITLE
Cash reports

### ISSUE THREAD

**Issue by VirrageS** [VirrageS/io-kawiarnie#67]
Jak powinno to wyglądać?

**Comment by mshario** [comment]
Model: pieniądze w kasie na początku zmiany, pieniądze w kasie na końcu zmiany, obrót w trakcie zmiany  kartami, wydatki: <na co, ile>,  łączna należność.

Formularz: pieniądze w kasie na początku zmiany, pienią∂ze w kasie na końcu zmiany podzielone na nominały (10 gr - 100 zł), karty, wydatki: na co i ile, np. dostawa makro 230zł, łączna należność.

**Comment by VirrageS** [comment]
Czy w modelu warto pamiętać także kto robił ten formularz?

**Comment by mshario** [comment]
Ta informacja na pewno jest potrzebna przy raporcie z kasy. Da się ją jakoś inaczej pamiętać niż w modelu?

**Comment by VirrageS** [comment]
Znaczy pewnie i można ale myślę, że to najbardziej sensowne będzie trzymać w modelu aktualnie zalogowanego użytkownika.

**Comment by mshario** [comment]
W czym jest lepsze to że użytkownik trzyma referencję do modelu od tego że raport trzyma referencję do pracownika?

**Comment by VirrageS** [comment]
Jeżeli raport trzyma referencję, to łatwiej jest się dostać. Bo wyświetlasz raport i bierzesz np. `raport.creator`. Jeżeli masz, że użytkownik trzyma referencję to znalezienie użytkownika dla raportu jest już trochę bardziej kłopotliwe.

Tym bardziej, że jeżeli użytkownik trzyma referencję do raportu, to będzie trzymał listę stworzonych raportów, a to już tak mało relacyjnie brzmi.

Po za tym nie mam więcej argumentów

**Comment by VirrageS** [comment]
Aaaa przepraszam. Ja źle zrozumiałem pytanie. W poprzednim komentarzu chodziło mi o model raportu, w którym będzie trzymana referencja do użytkownika, a nie że w modelu użytkownika referencja do modelu...

**Comment by mshario** [comment]
Tak, już też się zorientowałam że się źle zrozumieliśmy. To chyba wszystko jasne. 😃
