### ISSUE TITLE
Employee worked hours

### ISSUE THREAD

**Issue by VirrageS** [VirrageS/io-kawiarnie#77]

**Comment by knopt** [comment]
Model: data, godzina rozpoczęcia, godzina zakończenia.
Możliwość dodawania wielu 'zmian' podczas jednego dnia
Formularz dodawania przepracowanych godzin
Widoki - wykaz przepracowanych godzin w danym zakresie dat

**Comment by VirrageS** [comment]
1. Trzeba się zastanowić czy ten kto dodaje jest ustawiany jako ten, który będzie zapisany w modelu. Czy też dać możliwość wpisania kogoś innego np. poprzez wybór z listy - ale to już trochę się shady wydaje.
2. Trzeba pamiętać o sprawdzeniu zakresów. godzina zakończenia < 24. godzina rozpoczęcia > 0. dwie zmiany nie mogą na siebie nachodzić itp.
